package com.meizu.code.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.meizu.code.greendao.bean.BookBean;
import com.meizu.code.greendao.bean.BookIntroduceBean;
import com.meizu.code.greendao.bean.MeituanRecordBean;

import com.meizu.code.greendao.BookBeanDao;
import com.meizu.code.greendao.BookIntroduceBeanDao;
import com.meizu.code.greendao.MeituanRecordBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookBeanDaoConfig;
    private final DaoConfig bookIntroduceBeanDaoConfig;
    private final DaoConfig meituanRecordBeanDaoConfig;

    private final BookBeanDao bookBeanDao;
    private final BookIntroduceBeanDao bookIntroduceBeanDao;
    private final MeituanRecordBeanDao meituanRecordBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookBeanDaoConfig = daoConfigMap.get(BookBeanDao.class).clone();
        bookBeanDaoConfig.initIdentityScope(type);

        bookIntroduceBeanDaoConfig = daoConfigMap.get(BookIntroduceBeanDao.class).clone();
        bookIntroduceBeanDaoConfig.initIdentityScope(type);

        meituanRecordBeanDaoConfig = daoConfigMap.get(MeituanRecordBeanDao.class).clone();
        meituanRecordBeanDaoConfig.initIdentityScope(type);

        bookBeanDao = new BookBeanDao(bookBeanDaoConfig, this);
        bookIntroduceBeanDao = new BookIntroduceBeanDao(bookIntroduceBeanDaoConfig, this);
        meituanRecordBeanDao = new MeituanRecordBeanDao(meituanRecordBeanDaoConfig, this);

        registerDao(BookBean.class, bookBeanDao);
        registerDao(BookIntroduceBean.class, bookIntroduceBeanDao);
        registerDao(MeituanRecordBean.class, meituanRecordBeanDao);
    }
    
    public void clear() {
        bookBeanDaoConfig.clearIdentityScope();
        bookIntroduceBeanDaoConfig.clearIdentityScope();
        meituanRecordBeanDaoConfig.clearIdentityScope();
    }

    public BookBeanDao getBookBeanDao() {
        return bookBeanDao;
    }

    public BookIntroduceBeanDao getBookIntroduceBeanDao() {
        return bookIntroduceBeanDao;
    }

    public MeituanRecordBeanDao getMeituanRecordBeanDao() {
        return meituanRecordBeanDao;
    }

}
